train:
  _target_: src.datasets.YambdaDataset
  name: "train"
  inter_type: "listens"
  yambda_size: "50m"
  min_inter: 1000
  q: 0.9
  max_len: 100
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.YambdaDataset
  name: "test"
  inter_type: ${..train.inter_type}
  yambda_size: ${..train.yambda_size}
  min_inter: ${..train.min_inter}
  q: ${..train.q}
  max_len: ${..train.max_len}
  instance_transforms: ${transforms.instance_transforms.inference}
